apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: web-apps
spec:
  selector:
    app: django-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80            # External service port
      targetPort: 8000    # Container port defined in your deployment
      nodePort: 30080     # Node port (must be in range 30000–32767)
