
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: web-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: saisaiko/django-app-name:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
