name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | buildah login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        buildah build -t ${{ secrets.DOCKER_USERNAME }}/django-app-name:latest .
        buildah push ${{ secrets.DOCKER_USERNAME }}/django-app-name:latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config

    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f k8s/django-deployment.yaml

    - name: Force Restart Deployment (ensure image refresh)
      run: |
        kubectl rollout restart deployment django-app -n web-apps

    - name: Verify Deployment Rollout
      run: |
        kubectl rollout status deployment/django-app --namespace=web-apps --timeout=60s

    - name: Debug on Rollout Failure
      if: failure()
      run: |
        echo "Rollout failed. Fetching pod status..."
        kubectl get pods -n web-apps
        kubectl describe deployment django-app -n web-apps
        kubectl logs --tail=50 -l app=django-app -n web-apps || true
